# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        container_name: 'ms_encoder_app'
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/var/www/html'
        networks:
            - inte-rabbitmq_codeflix_rabbitmq
            - app
    mysql:
        image: 'mysql:8.0'
        ports:
            - '33306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: 'root'
            MYSQL_DATABASE: 'ms_encoder_video'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'root'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        command: [
                "--sql-mode=TRADITIONAL",
                "--character-set-server=latin1",
                "--collation-server=latin1_swedish_ci",
                "--default-authentication-plugin=mysql_native_password"
        ]
        volumes:
            - 'ms_encoder_mysql:/var/lib/mysql'
        networks:
            - app
networks:
    app:
        driver: 'bridge'
    inte-rabbitmq_codeflix_rabbitmq:
        external: true

volumes:
    ms_encoder_mysql:
        driver: local