#https://medium.com/laravel-docker-and-docker-compose/deploying-our-laravel-with-docker-swarm-part-3-1b93b657d094
version: "3"

services:
  ms_encoder_video_db:
    image: mysql:8.0.21
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=ms_encoder_videos
      - MYSQL_USER=catalogo_videos
      - MYSQL_PASSWORD=5124828
      - MYSQL_ROOT_PASSWORD=5124828
    networks:
      - ms_encoder_video
    volumes:
      - ms_encoder_video_db:/var/lib/mysql/
    ports:
      - "3306"
    command: ["--default-authentication-plugin=mysql_native_password"]

  ms_encoder_video:
    image: ms-encoder-video_ms_encoder_video:latest
    restart: always
    networks:
      - ms_encoder_video
    environment:
      - APP_ENV=production
      - APP_KEY=base64:k1FSp+yDOylxMlqGZh7wIm7os9+EK3OlRknNjP7mfUE=
      - DB_CONNECTION=mysql
      - DB_HOST=ms_encoder_video_db
      - DB_PORT=3306
      - DB_DATABASE=ms_encoder_videos
      - DB_USERNAME=catalogo_videos
      - DB_PASSWORD=5124828
      - GOOGLE_CLOUD_KEY_FILE=/var/www/html/storage/app/codeflix-298009-58b7e01f8396.json
      - GOOGLE_CLOUD_PROJECT_ID=codeflix-298009
      - GOOGLE_CLOUD_STORAGE_BUCKET=codemicrovideos
      - GOOGLE_CLOUD_STORAGE_PATH_PREFIX=
      - GOOGLE_CLOUD_STORAGE_API_URI=https://storage.cloud.google.com/codemicrovideos
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

networks:
  ms_encoder_video:

volumes:
  ms_encoder_video_db: